"""game_id

Revision ID: fae78eb4ee21
Revises: 8ce0f35c731f
Create Date: 2025-04-10 18:30:57.820599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae78eb4ee21'
down_revision: Union[str, None] = '8ce0f35c731f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'game_id')
    # ### end Alembic commands ###
